// examples/vue/src/pages/DashboardPage.vue
<script setup lang="ts">
import { useSession } from "@yackey-labs/yauth-go-ui-vue";
import { useRouter } from "vue-router";

const { user, isAuthenticated, loading, logout } = useSession();
const router = useRouter();

const handleLogout = async () => {
	await logout();
	router.push("/login");
};
</script>

<template>
  <h1>Dashboard</h1>
  <div v-if="loading">Loading...</div>
  <div v-else-if="isAuthenticated">
    <p>Logged in as <strong>{{ user?.email }}</strong></p>
    <p style="margin-top: 8px; color: #666; font-size: 14px;">
      Role: {{ user?.role }} |
      Email verified: {{ user?.email_verified ? "Yes" : "No" }}
    </p>
    <button style="margin-top: 16px;" @click="handleLogout">Logout</button>
  </div>
  <div v-else>
    <p>Not logged in.</p>
    <RouterLink to="/login">Go to login</RouterLink>
  </div>
</template>

// examples/solidjs/src/pages/DashboardPage.tsx
import { Show } from "solid-js";
import { useNavigate } from "@solidjs/router";
import { useYAuth } from "@yackey-labs/yauth-ui-solidjs";

export function DashboardPage() {
  const navigate = useNavigate();
  const { client, user, loading } = useYAuth();

  // user() and loading() are signal accessors — only call inside JSX or effects.
  // Destructuring { client, user, loading } from useYAuth is safe because
  // client is a plain object and user/loading are already accessor functions.

  const handleLogout = async () => {
    await client.logout();
    navigate("/login");
  };

  return (
    <>
      <h1>Dashboard</h1>
      <Show when={!loading()} fallback={<div>Loading...</div>}>
        <Show
          when={user()}
          fallback={
            <div>
              <p>Not logged in.</p>
              <a href="/login">Go to login</a>
            </div>
          }
        >
          {(u) => (
            <div>
              <p>
                Logged in as <strong>{u().email}</strong>
              </p>
              <p
                style={{
                  "margin-top": "8px",
                  color: "#666",
                  "font-size": "14px",
                }}
              >
                Role: {u().role} | Email verified:{" "}
                {u().email_verified ? "Yes" : "No"}
              </p>
              <button style={{ "margin-top": "16px" }} onClick={handleLogout}>
                Logout
              </button>
            </div>
          )}
        </Show>
      </Show>
    </>
  );
}
