// examples/vue/src/pages/LoginPage.vue
<script setup lang="ts">
import { LoginForm } from "@yackey-labs/yauth-go-ui-vue";
import { useRouter } from "vue-router";

const router = useRouter();
</script>

<template>
  <h1>Login</h1>
  <LoginForm @success="router.push('/dashboard')" />
  <p style="margin-top: 12px; font-size: 14px;">
    Don't have an account? <RouterLink to="/register">Register</RouterLink>
  </p>
</template>

// examples/solidjs/src/pages/LoginPage.tsx
import { useNavigate } from "@solidjs/router";
import { LoginForm } from "@yackey-labs/yauth-ui-solidjs";

export function LoginPage() {
	const navigate = useNavigate();

	return (
		<>
			<h1>Login</h1>
			<LoginForm onSuccess={() => navigate("/dashboard")} />
			<p style={{ "margin-top": "12px", "font-size": "14px" }}>
				Don't have an account? <a href="/register">Register</a>
			</p>
		</>
	);
}
