// examples/vue/src/pages/RegisterPage.vue
<script setup lang="ts">
import { RegisterForm } from "@yackey-labs/yauth-ui-vue";
import { ref } from "vue";
import { useRouter } from "vue-router";

const router = useRouter();
const successMessage = ref<string | null>(null);

const handleSuccess = (message: string) => {
	successMessage.value = message || "Registration successful! Please log in.";
	setTimeout(() => router.push("/login"), 2000);
};
</script>

<template>
  <h1>Register</h1>
  <div v-if="successMessage" class="message success">{{ successMessage }}</div>
  <RegisterForm v-else @success="handleSuccess" />
  <p style="margin-top: 12px; font-size: 14px;">
    Already have an account? <RouterLink to="/login">Login</RouterLink>
  </p>
</template>

// examples/solidjs/src/pages/RegisterPage.tsx
import { useNavigate } from "@solidjs/router";
import { createSignal, Show } from "solid-js";
import { RegisterForm } from "@yackey-labs/yauth-ui-solidjs";

export function RegisterPage() {
  const navigate = useNavigate();
  const [successMessage, setSuccessMessage] = createSignal<string | null>(null);

  const handleSuccess = (message: string) => {
    setSuccessMessage(message || "Registration successful! Please log in.");
    setTimeout(() => navigate("/login"), 2000);
  };

  return (
    <>
      <h1>Register</h1>
      <Show
        when={!successMessage()}
        fallback={<div class="message success">{successMessage()}</div>}
      >
        <RegisterForm onSuccess={handleSuccess} />
      </Show>
      <p style={{ "margin-top": "12px", "font-size": "14px" }}>
        Already have an account? <a href="/login">Login</a>
      </p>
    </>
  );
}
