// packages/ui-vue/src/components/OAuthButtons.vue
<script setup lang="ts">
import { useYAuth } from "../provider";

defineProps<{
	providers: string[];
}>();

const { client } = useYAuth();
const oauth = client.oauth;

const handleClick = (provider: string) => {
	window.location.href = oauth!.authorize(provider);
};

const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
</script>

<template>
	<div class="space-y-2">
		<button
			v-for="provider in providers"
			:key="provider"
			class="inline-flex h-9 w-full cursor-pointer items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
			type="button"
			@click="handleClick(provider)"
		>
			Sign in with {{ capitalize(provider) }}
		</button>
	</div>
</template>

// packages/ui-solidjs/src/components/oauth-buttons.tsx
import { type Component, For } from "solid-js";
import { useYAuth } from "../provider";

export interface OAuthButtonsProps {
	providers: string[];
}

export const OAuthButtons: Component<OAuthButtonsProps> = (props) => {
	const { client } = useYAuth();
	const oauth = client?.oauth;
	if (!oauth) return null;

	const handleClick = (provider: string) => {
		window.location.href = oauth.authorize(provider);
	};

	return (
		<div class="space-y-2">
			<For each={props.providers}>
				{(provider) => (
					<button
						class="inline-flex h-9 w-full cursor-pointer items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
						type="button"
						onClick={() => handleClick(provider)}
					>
						Sign in with {provider.charAt(0).toUpperCase() + provider.slice(1)}
					</button>
				)}
			</For>
		</div>
	);
};
